name: Build and Release Tauri HTML App

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: extract_version
        shell: bash
        run: |
          version=${GITHUB_REF#refs/tags/v}
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Bump Rust version in Cargo.toml
        run: |
          cargo install cargo-edit
          cargo set-version "${{ steps.extract_version.outputs.version }}" \
            --manifest-path src-tauri/Cargo.toml

      - name: Update version in tauri.conf.json
        run: |
          jq --arg v "${{ steps.extract_version.outputs.version }}" \
            'del(.package) | .version = $v' \
            src-tauri/tauri.conf.json > tmp.json && \
          mv tmp.json src-tauri/tauri.conf.json

      - name: Bump npm version & lockfile
        run: |
          npm install --no-save
          npm version "${{ steps.extract_version.outputs.version }}" --no-git-tag-version

      - name: Commit version updates
        uses: stefanzweifel/git-au
